### PR TITLE
Gen json from struct

### PR DESCRIPTION
**Pull request by tanyifeng**
We have demand that generate json string from modified struct variable, such as what we described in README.md:

```
    oci_container container;
    char *json_buf = NULL;

    memset(&container, 0, sizeof(oci_container));

    container.oci_version = "2";
    container.hostname = "ubuntu";
    /* Add other configuration. */
    /* ... ... */

    json_buf = oci_container_generate_json(&container, NULL, &err);
    if (json_buf == NULL)
      exit(EXIT_FAILURE);

    printf("The generated json string is:\n%s\n", json_buf);
```

So, we package lib `<yajl/yajl_gen.h>` to generate json string with struct we parsed from corresponding json-schema. Move some common static function to `oci_json_common.h oci_json_common.c`, and add tests to check whether we have generated correct json string or not.

Please point out if we have some error while adding this feature.

### CODE REVIEW

**Comment by tanyifeng** [comment]
CI failed at:
```
0.34s$ make -j $(nproc)
./src/generate.py ./runtime-spec/schema/config-schema.json src/oci_runtime_spec.h src/oci_runtime_spec.c container
./src/generate.py ./image-spec/schema/config-schema.json src/oci_image_spec.h src/oci_image_spec.c image
./src/generate.py ./image-spec/schema/image-index-schema.json src/oci_image_index_spec.h src/oci_image_index_spec.c image_index
./src/generate.py ./image-spec/schema/image-layout-schema.json src/oci_image_layout_spec.h src/oci_image_layout_spec.c image_layout
./src/generate.py ./image-spec/schema/image-manifest-schema.json src/oci_image_manifest_spec.h src/oci_image_manifest_spec.c image_manifest
make: *** No rule to make target `src/oci_json_common.c', needed by `src/oci_json_common.h'.  Stop.
make: *** Waiting for unfinished jobs....

The command "make -j $(nproc)" exited with 2.
```
Because using  `make -j $(nproc)` is so fast that the last command `./src/generate.py` is generating `oci_json_common.h` and make already started, generate.py and make have conflicts with open the same file.

**Comment by tanyifeng** [comment]
Since `oci_json_common.h` and `oci_json_comon.c` have nothing with all json-schema, is that appropriate to merge these file and `read-file.c read-file.h` ? Then we can still use `make -j` and decrease numbers of common file.

**Comment by tanyifeng** [comment]
ping @giuseppe

**Comment by giuseppe** [comment]
@tanyifeng thanks for this great feature!  I'd prefer that we can keep `make -j` as it is probably some missing dependency in the Makefile.  In any case it is not a blocking issue for this PR, I am going to merge it and I'll take a look afterwards at enabling `make -j` again

**Pull request merged**
